services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: beans-db
    ports:
      - "5432:5432"
    volumes:
      - data_sql:/var/lib/postgresql/data

volumes:
  data_sql: