services:
  beans_api:
    container_name: beans_api
    image: allthebeansapi:latest
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__BeansDbConnectionString: 'Host=postgres_db;Port=5432;Database=beans-db;User Id=<userId>;Password=<password>;'

  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: <userId>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: beans-db
    ports:
      - "5432:5432"
    volumes:
      - data_sql:/var/lib/postgresql/data

volumes:
  data_sql: